services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: test123!@#
      MYSQL_DATABASE: auth_test
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5

  fastapi_app:
    build: .
    container_name: fastapi_app
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_USER: root
      DB_PASSWORD: test123!@#
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: auth_test
    ports:
      - "8000:8000"
    volumes:
      - .:/app

volumes:
  db_data:
