"""create refresh_token_table

Revision ID: 96b62f2001c8
Revises: 0b136f33f1df
Create Date: 2026-06-24 13:02:51.356039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96b62f2001c8'
down_revision: Union[str, Sequence[str], None] = '0b136f33f1df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_refresh_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=36), nullable=False),
    sa.Column('refresh_token', sa.Text(), nullable=False),
    sa.Column('device_info', sa.String(length=255), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_refresh_tokens_id'), 'user_refresh_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_user_refresh_tokens_jti'), 'user_refresh_tokens', ['jti'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_refresh_tokens_jti'), table_name='user_refresh_tokens')
    op.drop_index(op.f('ix_user_refresh_tokens_id'), table_name='user_refresh_tokens')
    op.drop_table('user_refresh_tokens')
    # ### end Alembic commands ###
